version: "3.9"
services:
  web:
    image: nginx
    volumes:
    - ./persisted/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./persisted/data/www/:/data/www/
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
